query getBlog($slug: String!) {
  getObject(
    bucket_slug: "kemiljk"
    read_key: "uNXYQDbNTCWQyEaFjq44PUolieGKBuzePTaEdnDl0CHLcnJtPK"
    input: { slug: $slug }
  ) {
    title
    content
    metadata
    modified_at
    order
  }
}
