{
  getObjects(
    bucket_slug: "kemiljk"
    input: {
      read_key: "uNXYQDbNTCWQyEaFjq44PUolieGKBuzePTaEdnDl0CHLcnJtPK"
      type: "blogs"
    }
  ) {
    objects {
      _id
      slug
      title
      content
      metadata
      modified_at
      order
    }
    total
  }
}
