{
  getObjects(
    bucket_slug: "kemiljk"
    read_key: "uNXYQDbNTCWQyEaFjq44PUolieGKBuzePTaEdnDl0CHLcnJtPK"
    input: { limit: 0, query: { type: "blogs" } }
  ) {
    objects {
      id
      slug
      title
      content
      metadata
      modified_at
      order
    }
  }
}
